@baseUrl = http://127.0.0.1:8080/
@route = params
@url = {{baseUrl}}{{route}}
@content = application/json

### params only no path
GET {{url}}?name=SevenOfNine&age=42&location=voyager HTTP/1.
Content-Type: {{content}}


### params only and path
GET {{url}}/one?name=SevenOfNine&age=42&location=voyager HTTP/1.
Content-Type: {{content}}