@baseUrl = http://127.0.0.1:8080/
@route = todos
@url = {{baseUrl}}{{route}}
@content = application/json

###
// GET TODOS
GET {{url}}
Content-Type: application/json

###
// POST example
POST {{url}}
Content-Type: application/json

{
    "title": "A sexy title",
    "body": "A sexy note"
}

##### GET single by id
#### you need a valid id here depending on your runtime
#### mine is ty3doqq0vel08pwax6yr
GET {{url}}/ty3doqq0vel08pwax6yr
Content-Type: application/json


### you need an id here!!!
//PUT by id example
PUT {{url}}/ty3doqq0vel08pwax6yr
Content-Type: application/json

{
    "title": "A sexy title, updated",
    "body": "A sexy note, updated"
}


##### DELETE by id
DELETE {{url}}/ty3doqq0vel08pwax6yr
