@baseUrl = http://127.0.0.1:8080/
@route = users
@url = {{baseUrl}}{{route}}
@content = application/json


#pub struct User {
#    pub id: Option<String>,
#    pub username: String,
#    pub password: String,
#    pub role: String,
#}

###
POST {{url}}
Content-Type:  {{content}}

// enum type in role can give as safeness here try this vs
# {
#   "username" : "john doe",
#   "password" : "safepass",
#   "role" : "user"
# }


{
  "username" : "JohnUser",
  "password" : "Johns call",
  "role" : "User"
}


### get list
GET {{url}}
Content-Type: {{content}}

### get list by role
GET {{url}}/role=user
Content-Type: {{content}}

### by id e.g. lq6up5k73ooejrczl07p
GET {{url}}/lq6up5k73ooejrczl07p
Content-Type: {{content}}

###
PUT {{url}}/gyheq6tzk3c3yji7venb
Content-Type: {{content}}

{
   "username" : "test user",
   "password" : "safepass",
   "role" : "user"
}
