@baseUrl = http://127.0.0.1:8080/
@route = users
@url = {{baseUrl}}{{route}}
@content = application/json


#pub struct User {
#    pub id: Option<String>,
#    pub username: String,
#    pub password: String,
#    pub role: String,
#}

###
POST {{url}}
Content-Type:  {{content}}

{
  "username" : "john doe",
  "password" : "safepass",
  "role" : "user"
}


### get list
GET {{url}}
Content-Type: {{content}}

### by id e.g. gyheq6tzk3c3yji7venb
GET {{url}}/gyheq6tzk3c3yji7venb
Content-Type: {{content}}

###
PUT {{url}}/gyheq6tzk3c3yji7venb
Content-Type: {{content}}

{
   "username" : "test user",
   "password" : "safepass",
   "role" : "user"
}
